import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import path from 'path'
import frappeui from 'frappe-ui/vite'

export default defineConfig({
  plugins: [
    frappeui({
      frappeProxy: true,
      lucideIcons: true,
      jinjaBootData: false,
      buildConfig: {
        // A path under www/ (not public/) so Frappe actually renders it
        // through Jinja on each request — a plain public/ file is served as
        // a raw static asset with no template substitution at all, so
        // {{ csrf_token }}/{{ site_name }} below would ship as the literal,
        // unsubstituted string. www/frontend.py's get_context() supplies
        // both. This file's asset references (with their build hashes) get
        // fully regenerated by the copy step below on every `yarn build`.
        indexHtmlPath: '../my_new_app/www/frontend.html',
      },
    }),
    vue(),
  ],
  server: {
    port: 8080,
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, 'src'),
    },
  },
  build: {
    rollupOptions: {
      output: {
        // Vue/Vue Router rarely change between deploys (pinned versions,
        // not app code), but without this they're baked into the same
        // "index" chunk as our own app setup — so every deploy forces a
        // full re-download of all of it, even on a repeat visit where the
        // browser already has last week's identical framework code cached.
        // Splitting them out means only the (much smaller) chunk that
        // actually changed needs to be fetched again.
        //
        // Deliberately NOT grouping frappe-ui the same way: it's imported
        // from both `frappe-ui` (components) and `frappe-ui/editor`
        // (tiptap/prosemirror), and a broad `id.includes('frappe-ui')`
        // match pulls both into one chunk — merging the editor's ~500KB
        // gzipped weight into a chunk every page loads, undoing Rollup's
        // existing automatic split that keeps it out of pages that don't
        // use the editor (Login, Home, Profile, Settings, ...). Left to
        // Rollup's default chunking instead, same as tiptap/prosemirror
        // itself — see optimizeDeps.exclude below for why a second,
        // separately-bundled copy of tiptap would break at runtime.
        manualChunks(id) {
          if (!id.includes('node_modules')) return
          if (
            id.includes('node_modules/vue/') ||
            id.includes('node_modules/vue-router/') ||
            id.includes('node_modules/@vue/')
          ) {
            return 'vendor-vue'
          }
        },
      },
    },
  },
  optimizeDeps: {
    exclude: [
      'frappe-ui',
      // frappe-ui is excluded above (served as source, since it ships raw
      // .vue/.ts and esbuild's optimizer can't process .vue SFCs), but its
      // editor pulls in tiptap/prosemirror from multiple page entry points
      // (WritePost.vue, Messages.vue). Optimizing tiptap separately from
      // frappe-ui's own raw-served imports of it produces two distinct
      // module instances of the same package, which ProseMirror rejects at
      // runtime with "Adding different instances of a keyed plugin". Excluding
      // the whole tiptap graph too keeps it on native, single-instance ESM
      // resolution consistent with frappe-ui's own unbundled imports.
      '@tiptap/core',
      '@tiptap/pm',
      '@tiptap/vue-3',
      '@tiptap/starter-kit',
      '@tiptap/extensions',
      '@tiptap/suggestion',
      '@tiptap/markdown',
    ],
    include: [
      'feather-icons',
      'tippy.js',
      'engine.io-client',
      'socket.io-client',
      'debug',
    ],
  },
})
